trigger:
- main

pool:
  name: 'Ubuntu 20.10 VM'

steps:
- script: |
    export QEMU_AUDIO_DRV="none"
    python3 tester.py inputs.txt
  displayName: 'Run Tests'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonar'
    organization: 'therealxg'
    scannerMode: 'CLI'
    configMode: 'file'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Results'
  condition: always()
  inputs:
    targetPath: 'results.txt'
    artifact: 'Test Results'
    publishLocation: 'pipeline'