trigger:
- main

pool:
  name: 'Ubuntu 20.10 VM'

steps:
- script: |
    ./add.exp
  displayName: 'Run a multi-line script'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'add_expect.txt'
    artifact: 'Output Log'
    publishLocation: 'pipeline'